### ISSUE TITLE
Embed `copy-on-click.js` in a file instead of inline

### ISSUE THREAD

**Issue by altrisi** [FabricMC/MappingPoet#11]
Once again, not sure how viable this is, but since the `copy-on-click` script is the same for every class, couldn't it be added as a reference to a `.js` file at the root of the javadoc?

It's not (at least currently) a big deal, since it's 558 bytes (+start/end `<script>` tags), but those could be shortened to around 50 depending on the depth of the class, with something like:

```html
<script src="../../../../../copy-on-click.js"></script>
```

(if there are 5775 classes, according to intermediary counter, that would save around 2,9MB per javadoc build)

This would also allow browsers to cache it when loading it remotely, but would need a way to figure out the depth of the current class in order to correctly point to the script.

~BTW, how do you produce yarn javadocs with this? I've not been able to do it even once yet. I'm using 0.2.1 (still in Java 11) mappingpoet there (always getting `javadoc: error - cannot read Input length = 1` in `:javadoc` task).~ I've finally been able to produce docs. The problem was solved by adding `-Dfile.encoding=UTF-8` as a parameter for Gradle. It also happens in upstream yarn.

----

Edit (not sure why not a new comment):

The `{@docRoot}` equivalent could be produced by a function like:

```java
private static void docRoot(Element element, StringBuilder builder) {
	String type = element.asType().toString();
	int dotIndex = type.indexOf('.');
    while (dotIndex != -1) {
        builder.append("../");
        dotIndex = type.indexOf('.', dotIndex + 1);
    }
}
```

Then this would be done with a way to save the script to the actual `{@docRoot}`.

**Comment by liach** [comment]
I think if we do try expand this, we might need a custom doclet than a simple taglet. I don't think standard doclet allows you to include custom script; I only recall an option for extra css stylesheets.

**Comment by liach** [comment]
These are what the standard doclet supports: https://docs.oracle.com/en/java/javase/15/docs/specs/man/javadoc.html#standard-doclet-options
for reference.

**Comment by liach** [comment]
Hmm, looks like it's easier than I thought. We can just add like
```html
<script src="{@docRoot}/copy-on-click.js"></script>
```
(per https://stackoverflow.com/a/3130419 on how to use it)
and use gradle to copy the `copy-on-click.js` to doc root in yarn.

**Comment by liach** [comment]
9ca22d4ab3a5504d34502aed270c5b67cbe586ad relates to this one.

**Comment by liach** [comment]
Integrated in https://github.com/FabricMC/yarn/pull/1934/commits/688f6fb58626d51750ca6d5cc60bfc4ec0bb3072
