### ISSUE TITLE
Consider outputing package visibility info

### ISSUE THREAD

**Issue by liach** [FabricMC/MappingPoet#15]
Currently, we are plagued by package misplacements in yarn. I wonder if it will be worthy to put these information in generated javadoc, especially for like yarn contributors.

@modmuss50 I want to hear especially from you on this question.

**Comment by liach** [comment]
Note: If we do output this, I plan to output in a fashion similar to java's object inheritance tree (except we will omit nested classes and clusters with only one class), where the header for each group is their current shared package

**Comment by modmuss50** [comment]
Im not sure wht the use of this would be?

**Comment by liach** [comment]
right, we've discussed before that enforcing going through loader is better. will make that a javadoc notice instead
