### ISSUE TITLE
Annotation replacement

### ISSUE THREAD

**Issue by liach** [FabricMC/MappingPoet#16]
https://github.com/FabricMC/fabric-loom/blob/57c9a8f3209121f22e84b8b01b64f1093256f1d3/src/main/java/net/fabricmc/loom/configuration/providers/minecraft/MinecraftMappedProvider.java#L46-L50

Should be easy to do. Also avoids tricky bad javadoc problems from jsr305 annotations

**Comment by modmuss50** [comment]
Prob easier to do this when remapping the jar to intermediary in yarn.

**Comment by liach** [comment]
Should this be integrated into tiny remapper or be a separate step?

edit: read the loom code, it's just one step in tiny builder, easy

**Comment by modmuss50** [comment]
Just take the loom code and put it here: <https://github.com/FabricMC/yarn/blob/21w07a/build.gradle#L827> its just that map and https://github.com/FabricMC/fabric-loom/blob/57c9a8f3209121f22e84b8b01b64f1093256f1d3/src/main/java/net/fabricmc/loom/configuration/providers/minecraft/MinecraftMappedProvider.java#L132
